# Generated by Django 4.2 on 2023-05-03 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='weight',
            new_name='pweight',
        ),
    ]
