# Generated by Django 4.2 on 2023-05-03 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_weight_person_pweight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_active',
        ),
    ]
