# Generated by Django 4.2 on 2023-05-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_person_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='pweight',
            new_name='weight',
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
